[app]
name = "axum-health-service"
version = "0.1.0"
host = "127.0.0.1"
port = 3000
log_level = "info"

[database]
host = "localhost"
port = 3306
username = "eddie"
password = "password"
database = "eddie"
pool_size = 10
timeout_seconds = 30

